import { TabWidget, StandardListView, ProgressIndicator} from "std-widgets.slint";

export struct SidebarItem {
    text: string,
}

export global SidebarItems {
    in property <[SidebarItem]> drive_list: [];
}

export component StorageIndicator inherits ProgressIndicator {
    in property <percent> pct: 0%;
    width: 100%;
    height: 10px;
    progress: pct;
}

export component DriveList inherits StandardListView {
    width: 200px;
    //model: SidebarItems.drive-list;
    for sbitem[i] in SidebarItems.drive-list: Text {
        text: sbitem.text;
        //height: 10px;
        y: parent.y + (i*15px);
    }
}

export component MainWindow {
    
    HorizontalLayout {
        width: 100%;
        VerticalLayout{
            Text {
                text: "Drives";
            }
            DriveList {}
        }
        TabWidget {
            Tab {
                title: "1";
            }
        }
    }
}
