import { Button, LineEdit, CheckBox, StandardButton } from "std-widgets.slint";

//Generic adapter for all 3 'create new' windows
export global CreateNewAdapter {
    in property <string> path_to_directory;
    in-out property <string> name;
    in-out property <string> link_target;
    in-out property <string> warning;
    callback cancel();
    callback ok();
    callback edited(string);
}

export component CreateNewFile inherits Window {
    in-out property <length> win_height <=> self.height;
    in-out property <length> win_width <=> self.width;
    always-on-top: true;
    height: 140px;
    title: "Create new file";
    width: 600px;
    forward-focus: name;

    Text {
        font-size: 13px;
        overflow: TextOverflow.elide;
        text: "Creating a new file in '" + CreateNewAdapter.path_to_directory + "'";
        y: 20px;
        x: 20px;
    }

    name := LineEdit {
        text <=> CreateNewAdapter.name;
        y: 50px;
        x: 20px;
        width: parent.width - 40px;
        edited(s) => {
            CreateNewAdapter.edited(s);
        }
        accepted => {
            CreateNewAdapter.ok();
        }
    }

    cancel_btn := StandardButton {
        kind: cancel;
        x: parent.width - self.width - 20px;
        y: parent.height - 45px;

        clicked => {
            CreateNewAdapter.cancel();
        }
    }

    ok_btn := StandardButton {
        kind: ok;
        x: parent.width - cancel-btn.width - self.width - 30px;
        y: parent.height - 45px;
        clicked => {
            CreateNewAdapter.ok();
        }
    }

    Text {
        x: 20px;
        y: parent.height - 35px;
        text: CreateNewAdapter.warning;
        color: Colors.red;
        font-weight: 800;
    }
}
