export global Icons {
    in property <image> drive: @image-url("icons/drive.svg");
    in property <image> left-arrow: @image-url("icons/left-arrow.svg");
    in property <image> right-arrow: @image-url("icons/right-arrow.svg");
    in property <image> cross: @image-url("icons/cross.svg");
    in property <image> up-arrow: @image-url("icons/up-arrow.svg");
    in property <image> down-arrow: @image-url("icons/down-arrow.svg");
    in property <image> file: @image-url("icons/file.svg");
    in property <image> folder: @image-url("icons/folder.svg");
}
