import { ScrollView } from "std-widgets.slint";

export struct SidebarItem {
    text: string,
    internal_path: string,
}

export global SidebarItems {
    in property <[SidebarItem]> drive_list: [];
    callback drive_clicked(SidebarItem);
    callback left_arrow_clicked();
    callback right_arrow_clicked();
}

export component DriveListItem {
    in property <string> text;
    callback clicked <=> touch.clicked;

    min-height: 30px;

    rect := Rectangle {
        border-radius: 4px;
        border-width: 1px;
        border-color: black;
    }
    HorizontalLayout {
        padding-left: 2px;
        padding-top: 2px;
        padding-bottom: 2px;
        padding-right: 2px;
        spacing: 5px;

        Text {
            horizontal-stretch: 1;
            font-size: 14px;
            text: text;
            vertical-alignment: center;
        }

        /*i-icon := Image {
            horizontal-stretch: 0;
            visible: false;
            source: Images.check;
            colorize: Theme.palette.lemon-green;
        }*/
        
    }
    touch := TouchArea {}
}

export component DriveList {
    in property <[SidebarItem]> model;
    in property <length> _width <=> self.width;

    scrollview := ScrollView {
        VerticalLayout {
            alignment: start;
            spacing: 2px;
            for item[i] in model : DriveListItem {
                clicked => {
                    SidebarItems.drive-clicked(item);
                }
                private property <length> offset: scrollview.viewport-y + i * (self.height + parent.spacing);
                text: item.text;
                animate opacity { duration: 50ms;  }
            }
        }
    }
}

export component NavArrows {
    in property <length> _height;
    height: _height + 3px;//padding
    Rectangle {
        x: parent.x;
        y: parent.y;
        width: _height;
        height: _height;
        background: yellow;
        //callback clicked <=> touchL.clicked;
        Text {text: "<"; vertical-alignment: center;} /*Image todo*/
        TouchArea {
            clicked => { SidebarItems.left-arrow-clicked();}
        }
    }
    Rectangle {
        x: parent.x + _height + 1px;
        y: parent.y;
        width: _height;
        height: _height;
        background: purple;
        Text {text: ">"; vertical-alignment: center;} /*Image todo*/
        TouchArea {
            clicked => { SidebarItems.right-arrow-clicked(); }
        }
    }
}
