export struct ThemeImpl {
    //Background colors
    background_color_main: brush,
    background_color_sidebar: brush,
    background_color_tabs: brush,
    
    selected_tab_color: brush,
    unselected_tab_color: brush,

    //Unused
    hover_color_main: brush,
    hover_color_sidebar: brush,

    //Text
    text_color_main: brush,
    text_color_sidebar_header: brush,
    text_color_tabs: brush,

    //Fonts
    font_size_main: length,
    font_size_sidebar_item: length,
    font_size_sidebar_header: length,
    font_size_tabs: length,
    font_size_crumbs: length,
    font_size_header: length,

    //Colors
    arrow_color: brush,
    separator_color: brush,
    red_color: brush,
    header_arrows_color: brush,
    file_icon_color: brush,
    folder_icon_color: brush,
    selected_file_color: brush,

    //Padding
    main_padding_left: length,
    main_padding_top: length,
    main_padding_bot: length,
    main_padding_right: length,

    //Sizes
    sidebar_width: length,
    tab_height: length,
    breadcrumbs_height: length,
    

}

export global Theme {
    in property <ThemeImpl> dark: {
        background_color_main: #131416,
        background_color_sidebar: #131416,
        background_color_tabs: #262626,

        selected_tab_color: #131416,
        unselected_tab_color: #262626,

        hover_color_main: #292929,
        hover_color_sidebar: #292929,

        text_color_main: #d0d0d0,
        text_color_sidebar_header: #d0d0d0,
        text_color_tabs: #d0d0d0,

        font_size_sidebar_item: 14px,
        font_size_sidebar_header: 16px,
        font_size_tabs: 14px,
        font_size_crumbs: 18px,
        font_size_header: 14px,

        arrow_color: #d0d0d0,
        separator_color: #303335,
        red_color: #ee5396,
        header_arrows_color: #4e5155,
        file_icon_color: #d0d0d0,
        folder_icon_color: #d0d0d0,
        selected_file_color: #4e5155,

        main_padding_left: 10px,
        main_padding_top: 5px,
        main_padding_bot: 5px,
        main_padding_right: 5px,

        sidebar_width: 200px,
        tab_height: 30px,
        breadcrumbs_height: 30px,
    };
    in property <ThemeImpl> light: {
        background_color_main: #FFFFFF,
    };
    in property <ThemeImpl> darker: {
        background_color_main: #000000,
    };
    in-out property <ThemeImpl> current: dark;
    in-out property <length> width; 
    in-out property <length> height; 
    public function setup(current_theme_str: string, _w: int, _h: int)  {
        if (current-theme_str == "dark") {
            current = dark;
        }
        else if (current-theme_str == "light") {
            current = light;
        }
        width = _w*1px;
        height = _h*1px;
    }
}


