/*
    Parameters: x, y, height, background
    Drawn from (x,y) down to (x, y+height)
*/
export component HSeparator inherits Rectangle {
    width: 1px;
}
/*
    Parameters: x, y, width, background
    Drawn form (x,y) to (x+width, y)
*/
export component VSeparator inherits Rectangle {
    height: 1px;
}

//An i64 split into two i32. Needed to store things like sizes
export struct _i64 {
    a: int,
    b: int,
}
